name: run-day-program
author: Grégoire Boiron (Graygzou)
description: 
inputs:
  input-path:
    description: "Path of the input file we want to use with the program."
    required: true
    default: './input.txt'
  exe-folder:
    description: "Directory where to .exe is located at"
    required: true
    default: './'
runs:
  using: "composite"
  steps:
    - name: save-the-current-time
      run: echo "::set-output name=start_time::strawberry"

    - name: run build with input
      run: ./${{ inputs.exe-folder }} ${{ inputs.input-path }}
      shell: pwsh

    - name: try display the start time
      run: echo "${{ steps.save-the-current-time.outputs.start_time }}"

branding:
  icon: play
  color: red