name: create-image-chart-url
author: Grégoire Boiron (Graygzou)
description: 
inputs:
  data:
    description: "Array of JSON object containing same properties to display and compare easily."
    required: true
    default: '[]'
outputs:
  chart-url:
    description: "Full url using the image-chart API"
    value: ${{ steps.compose-url.outputs.full-url }}
runs:
  using: "composite"
  steps:
    - name: TEST 1
      id: test1
      run: |
        echo ${{ fromJSON(inputs.data) }}
        echo ${{ fromJSON(inputs.data) }}.*.name
        echo ${{ fromJSON(inputs.data) }}.*.time
      shell: bash

    - name: TEST 2
      id: test2
      run: |
        echo ${{ join(inputs.data.*.time, ',') }}
      shell: bash
      
    - name: Build URL prefix
      id: url-prefix
      run: |
        prefix="https://image-charts.com/chart?chbh=a&chbr=5&"
        colors=printf %s "chco=fdb45c,27c9c2,1869b7" | jq -sRr @uri
        echo "::set-output name=URL::$($prefix$colors)"
      shell: bash
        
    - name: Build rendering parameters
      id: url-rendering
      run: |
        bounds="chds=0,120"
        textmarkers="chm=N,000000,0,,10|N,000000,1,,10|N,000000,2,,10"
        margins="chma=0,0,10,10"
        size="chs=700x150"
        type="cht=bhg"
        axisLabelStyles="chxs=0,000000,0,0,_"
        title="chtt=Title"
        visibleAxes="chxt=y"
        url=${{ printf %s "$bounds&$textmarkers&$margins&$size&$type&$axisLabelStyles&$title&$visibleAxes" | jq -sRr @uri }}
        echo "::set-output name=URL::$url"
      shell: bash
      
    - name: Build data parameters
      id: url-data
      run: |
        data=${{ join(inputs.data.*.time, ',') }}
        echo $data
        echo "::set-output name=URL::$data"
      shell: bash

    - name: Compose the final URL
      id: compose-url
      run: |
        finalurl=${{ steps.url-prefix.outputs.URL }}${{ steps.start-timer.outputs.URL }}${{ steps.url-rendering.outputs.URL }}
        echo $finalurl
        echo "::set-output name=full-url::$finalurl"
      shell: bash

branding:
  icon: play
  color: blue
