name: MSBuild

on: [push]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: src/AdventOfCode2020/

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release
  
  # Platform used to run msbuild command
  PLATFORM: x64

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      # Add additional options to the MSBuild command line here (like platform or verbosity level).
      # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}

    - name: Upload builds
      uses: actions/upload-artifact@v2
      with:
        name: builds
        path: ${{env.SOLUTION_FILE_PATH}}${{env.PLATFORM}}/${{env.BUILD_CONFIGURATION}}
  
  execute:
    runs-on: windows-latest
    needs: [build]

    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: builds
          path: ${{env.BUILD_CONFIGURATION}}/

      - name: run test build
        run: |
          echo ${env:PATH}
          dir
          cd ..
          dir
          cd ${{ env.SOLUTION_FILE_PATH }}
          dir
          Get-Content Day10-AdapterArray/input.txt
        shell: pwsh
        working-directory: ${{env.GITHUB_WORKSPACE}}

      - name: run test build
        run: |
          ./${{env.BUILD_CONFIGURATION}}/Day10-AdapterArray.exe
        shell: pwsh
      
