name: MSBuild

on: [push]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: src/AdventOfCode2020/

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release
  
  # Platform used to run msbuild command
  PLATFORM: x64

  REPOSITORY_NAME: advent-of-code-2020

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      # Add additional options to the MSBuild command line here (like platform or verbosity level).
      # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}

    - name: Upload builds
      uses: actions/upload-artifact@v2
      with:
        name: builds
        path: ${{env.SOLUTION_FILE_PATH}}${{env.PLATFORM}}/${{env.BUILD_CONFIGURATION}}
  
  execute-day-1:
    runs-on: windows-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: builds
          path: ${{env.BUILD_CONFIGURATION}}/

      - name: test-custom-action
        uses: ./.github/actions/run-day-program
        with:
          input-path: ${{env.GITHUB_WORKSPACE}}/${{ env.SOLUTION_FILE_PATH }}Day1-ReportRepair/input.txt
          exe-folder: ${{env.BUILD_CONFIGURATION}}/Day1-ReportRepair.exe
      
    execute-day-10:
    runs-on: windows-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: builds
          path: ${{env.BUILD_CONFIGURATION}}/

      - name: test-custom-action
        uses: ./.github/actions/run-day-program
        with:
          input-path: ${{env.GITHUB_WORKSPACE}}/${{ env.SOLUTION_FILE_PATH }}Day10-AdapterArray/input.txt
          exe-folder: ${{env.BUILD_CONFIGURATION}}/Day10-AdapterArray.exe
      
