name: test-image-creation

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Create graph url 1
        id: create-graph-url
        uses: ./.github/actions/create-graph-img
        with:
          data-array: "[5, 10, 7, 13]"

      - name: Test
        run: |
          urlRegex="\[\!\[chart\]\(.*\)\]"
          urlReplacement="[![chart](${{ steps.create-graph-url.outputs.chart-url }})]"
          escapedUrlReplacement=$(printf '%s\n' "$urlReplacement" | sed -e 's/[\/&]/\\&/g')
          sed -i "s/$urlRegex/$escapedUrlReplacement/g" README.md

      - name: Config bot
        run: |
          git config user.email ${{ BOT_ACCOUNT_MAIL }}
          git config user.name ${{ BOT_ACCOUNT_NAME }}

      - name: Git
        run: |
          git status
          git add README.md
          git commit -m "= Update README graph with new data"
          git push
