name: test-image-creation

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repo-token: ${{ secrets.ACCESS_TOKEN }}

      - name: Create graph url 1
        id: create-graph-url
        uses: ./.github/actions/create-graph-img
        with:
          data-array: "[5, 10, 7, 13]"

      - name: Output final url 1
        run: |
          echo '${{steps.create-graph-url.outputs.chart-url}}'
          echo ${{ toJSON(steps.create-graph-url.outputs.chart-url) }}

      - name: Test
        run: |
          urlRegex="\[\!\[chart\]\(.*\)\]"
          urlReplacement="[![chart](${{ steps.create-graph-url.outputs.chart-url }})]"
          escapedUrlReplacement=$(printf '%s\n' "$urlReplacement" | sed -e 's/[\/&]/\\&/g')
          echo $urlReplacement
          echo $escapedUrlReplacement
          sed -e "s/$urlRegex/$escapedUrlReplacement/g" README.md
          cat README.md
          git status

      - name: Git
        run: git status
